[package]
name = "imu"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Interface for interacting with various IMU devices"
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
name = "imu"
crate-type = ["rlib"]

[dependencies]
hexmove = "0.1.6"
hiwonder = "0.1"
linux_bno055 = "0.0.6"
socketcan = "3.3.0"
log = "0.4"
