name: Python Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-base-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      PYO3_PYTHON: /opt/hostedtoolcache/Python/3.11.11/x64/bin/python3.11
      PYTHON_INCLUDE_DIR: /opt/hostedtoolcache/Python/3.11.11/x64/include/python3.11
      PYTHON_LIB_DIR: /opt/hostedtoolcache/Python/3.11.11/x64/lib
      LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.11/x64/lib:$LD_LIBRARY_PATH
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y libudev-dev pkg-config python3.11-dev libpython3.11-dev
          # Create symlinks to ensure libraries are found
          sudo ln -sf /opt/hostedtoolcache/Python/3.11.11/x64/lib/libpython3.11.so /usr/lib/
          sudo ln -sf /opt/hostedtoolcache/Python/3.11.11/x64/lib/libpython3.11.so.1.0 /usr/lib/

      - name: Restore cache
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ env.pythonLocation }}
            .mypy_cache/
          key: new-python-requirements-${{ env.pythonLocation }}-${{ github.event.pull_request.base.sha || github.sha }}
          restore-keys: |
            new-python-requirements-${{ env.pythonLocation }}
            new-python-requirements-

      - name: Install package
        run: |
          pip install --upgrade --upgrade-strategy eager --extra-index-url https://download.pytorch.org/whl/cpu -e '.[dev]'

      - name: Run static checks
        run: |
          mkdir -p .mypy_cache
          make static-checks

      - name: Run unit tests
        run: |
          make test

      - name: Save cache
        uses: actions/cache/save@v3
        if: github.ref == 'refs/heads/master'
        with:
          path: |
            ${{ env.pythonLocation }}
            .mypy_cache/
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
